Homework 3 robots
AlbertMukhammadiev/University pull request #48
Opened 2016-12-26 15:30 UTC by AlbertMukhammadiev

2016-12-28 19:57 UTC, yurii-litvinov requested changes

2016-12-28 19:57 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots.Tests/RobotsTest.cs
> +        Graph monochromeGraph;
Лучше явно указывать модификаторы видимости для полей

2016-12-28 19:57 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots.Tests/RobotsTest.cs
> +
Лишняя пустая строчка

2016-12-28 19:57 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            }
👎

2016-12-28 19:57 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            visitedNodes.RemoveRange(0, visitedNodes.Count);
мм? Это, часом, не Clear()?

2016-12-28 19:57 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            buffer.RemoveRange(0, buffer.Count);
И тут

2016-12-28 19:57 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            }
Что за хитрости? :) Попытка сделать значения уникальными? Для этого есть https://msdn.microsoft.com/en-us/library/bb359438(v=vs.110).aspx или даже https://msdn.microsoft.com/en-us/library/bb348436(v=vs.110).aspx

2016-12-28 20:01 UTC, AlbertMukhammadiev commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            }
после того как я использовал distinct() я уже не мог обращаться к объекту как к списку)

2016-12-28 20:04 UTC, AlbertMukhammadiev commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            }
да это было глупо :(

2016-12-28 20:08 UTC, yurii-litvinov commented on Third_semestr/Homework_3/Robots/Robots/Graph.cs
> +            }
https://msdn.microsoft.com/en-us/library/bb342261(v=vs.100).aspx

2016-12-29 08:32 UTC, yurii-litvinov approved these changes

2017-02-23 17:32 UTC, merged