beta-reduction
AlbertMukhammadiev/University pull request #59
Opened 2017-03-16 11:34 UTC by AlbertMukhammadiev

2017-03-19 13:15 UTC, yurii-litvinov requested changes

2017-03-19 13:15 UTC, yurii-litvinov commented on Fourth_semestr/Homework_3/Beta-reduction.tex
> +\[  (({\lambda} a.({\lambda} b.bb)({\lambda} b.bb))b)(({\lambda} c.(cb))({\lambda} a.a))  \]
Я бы всё-таки хотел пробелы между b и b, иначе вдруг это переменная с именем `bb`

2017-03-19 13:15 UTC, yurii-litvinov commented on Fourth_semestr/Homework_3/Beta-reduction.tex
> +\[  (({\lambda} a.({\lambda} b.bb)({\lambda} b.bb))b)(({\lambda} c.(cb))({\lambda} a.a))  \]
И ещё хочется стрелочку с маленькой буквой \beta :)

2017-03-19 13:15 UTC, yurii-litvinov commented on Fourth_semestr/Homework_3/Beta-reduction.tex
> +\[  (({\lambda} b.bb)({\lambda} b.bb)({\lambda} b.bb))(b)\]
Мм, почему?

2017-03-19 13:41 UTC, AlbertMukhammadiev commented on Fourth_semestr/Homework_3/Beta-reduction.tex
> +\[  (({\lambda} b.bb)({\lambda} b.bb)({\lambda} b.bb))(b)\]
почему выражение расходится?

2017-06-01 21:27 UTC, yurii-litvinov approved these changes

2017-06-02 01:56 UTC, merged