Homework5 correctnessofbracketsequence
AlbertMukhammadiev/University pull request #60
Opened 2017-03-30 09:07 UTC by AlbertMukhammadiev

2017-05-01 21:44 UTC, yurii-litvinov requested changes
Тесты подправьте, пожалуйста

2017-05-01 21:44 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +﻿module Test. `` gfghj ``
Хм, неплохое название модуля :)

2017-05-01 21:44 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +let ``null string`` =
Тут "()" не хватает

2017-05-01 21:44 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +Check.Quick check
Выводит
```
Falsifiable, after 1 test (0 shrinks) (StdGen (765941424,296296949)):
Original:
"["
```
Что совершенно разумно, впрочем :)

2017-05-03 06:52 UTC, AlbertMukhammadiev commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +﻿module Test. `` gfghj ``
Кстати, я не понимаю для чего такая возможность, это название ведь нигде не отображается?
Или это прилично вместо module Tests написать module ``tests that checks "function name"``?

2017-05-31 15:52 UTC, AlbertMukhammadiev commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +Check.Quick check
Это ведь для этого и нужно, чтобы увидеть где функция выдает false?

2017-06-01 21:38 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +Check.Quick check
Но это же должен быть автоматический тест :) Он должен проверять, что на тех случаях, когда функция должна выдавать false, она выдаёт false, а на всех остальных --- true. Причём, не в консоль, а кидать исключение, чтобы NUnit мог пометить тест как проваленный

2017-06-01 21:39 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/CorrectnessOfBracketSequence/CorrectnessOfBracketSequence/Tests.fs
> +﻿module Test. `` gfghj ``
Не, модули лучше по-человечески называть, они будут видны из других дотнетовских языков как статические классы

2017-09-19 18:29 UTC, merged