phone book
AlbertMukhammadiev/University pull request #62
Opened 2017-04-14 06:42 UTC by AlbertMukhammadiev

2017-05-06 21:28 UTC, yurii-litvinov requested changes

2017-05-06 21:28 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/PhoneBook/PhoneBook/Book.fs
> +let path = "C:\Users\Альберт\Documents\GitHub\University\Fourth_semestr\Homework_5\PhoneBook\PhoneBook\Book.txt"
Это всё потому, что тесты в Visual Studio запускаются в своей отдельной папке, и чтобы ресурсы были им доступны, надо их либо создавать прямо по ходу тестового сценария, либо включать файл в проект со свойством "Copy to output directory", установленным в "Copy always"

2017-05-06 21:28 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/PhoneBook/PhoneBook/Book.fs
> +let mutable buffer = List.empty
Здесь ещё нельзя mutable, это как раз задача на то, что в функциональном стиле тоже можно писать обычные интерактивные программы

2017-05-06 21:28 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/PhoneBook/PhoneBook/Program.fs
> +    let query = System.Console.ReadLine()
Надо какой-то хелп выводить

2017-06-01 21:45 UTC, yurii-litvinov requested changes
Если файла нет, то падает, нехорошо

2017-06-01 21:45 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/PhoneBook/PhoneBook/Book.fs
> +                yield (record.[0], record.[1]) }
Что-то копипаст

2017-06-01 21:45 UTC, yurii-litvinov commented on Fourth_semestr/Homework_5/PhoneBook/PhoneBook/Book.fs
> +    let record = Seq.tryFind (fun (x, y) -> number = y) records
Этак мы ищем только по записям, которые есть в файле, но добавляем новые записи мы в список, который в памяти, поэтому если добавить запись и тут же попробовать её найти, то не найдём

2017-06-02 02:53 UTC, AlbertMukhammadiev commented on Fourth_semestr/Homework_5/PhoneBook/PhoneBook/Book.fs
> +    let record = Seq.tryFind (fun (x, y) -> number = y) records
ну а зачем тогда метод save нужен..

2017-06-02 08:51 UTC, yurii-litvinov approved these changes
Круто, зачтена.

2017-06-02 08:59 UTC, merged